name: Playwright Tests Auto Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14

  create-pr:
    name: Create PR
    needs: test
    if: needs.test.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Open PR if missing
        uses: actions/github-script@v7
        env:
          BRANCH: ${{ github.ref_name }}
        with:
          script: |
            const branch = process.env.BRANCH;
            const { owner, repo } = context.repo;

            async function branchHasDiff() {
              try {
                const cmp = await github.rest.repos.compareCommits({ owner, repo, base: 'main', head: branch });
                const files = cmp.data.files || [];
                core.info(`Files different vs main: ${files.length}`);
                return files.length > 0;
              } catch (e) {
                core.warning(`Compare failed (maybe main missing). Proceeding to create PR. Reason: ${e.message}`);
                return true; // assume diff so first PR can be created
              }
            }

            if (!(await branchHasDiff())) {
              core.info('No changes vs main; skipping PR creation.');
              return;
            }

            const existing = await github.rest.pulls.list({ owner, repo, head: `${owner}:${branch}`, base: 'main', state: 'open' });
            if (existing.data.length) {
              core.info(`PR already exists: #${existing.data[0].number}`);
              return;
            }

            const title = `Auto PR from ${branch}`;
            const body = `Automated PR after successful Playwright tests on branch ${branch}.`;
            const pr = await github.rest.pulls.create({ owner, repo, head: branch, base: 'main', title, body });
            core.info(`Created PR #${pr.data.number}`);